using Subtle.Model.Responses;

namespace Subtle.Model
{
	/// <summary>
	/// Generated from http://api.opensubtitles.org:80/xml-rpc at 10/10/2015 16:34:57.
	/// </summary>
	public static class OSDbConfig
	{
		public static Language[] Languages => new[]
		{
			new Language { Id = "afr", Iso639Code = "af", Name = "Afrikaans" },
			new Language { Id = "alb", Iso639Code = "sq", Name = "Albanian" },
			new Language { Id = "ara", Iso639Code = "ar", Name = "Arabic" },
			new Language { Id = "arm", Iso639Code = "hy", Name = "Armenian" },
			new Language { Id = "baq", Iso639Code = "eu", Name = "Basque" },
			new Language { Id = "bel", Iso639Code = "be", Name = "Belarusian" },
			new Language { Id = "ben", Iso639Code = "bn", Name = "Bengali" },
			new Language { Id = "bos", Iso639Code = "bs", Name = "Bosnian" },
			new Language { Id = "bre", Iso639Code = "br", Name = "Breton" },
			new Language { Id = "bul", Iso639Code = "bg", Name = "Bulgarian" },
			new Language { Id = "bur", Iso639Code = "my", Name = "Burmese" },
			new Language { Id = "cat", Iso639Code = "ca", Name = "Catalan" },
			new Language { Id = "chi", Iso639Code = "zh", Name = "Chinese (simplified)" },
			new Language { Id = "zht", Iso639Code = "zt", Name = "Chinese (traditional)" },
			new Language { Id = "zhe", Iso639Code = "ze", Name = "Chinese bilingual" },
			new Language { Id = "hrv", Iso639Code = "hr", Name = "Croatian" },
			new Language { Id = "cze", Iso639Code = "cs", Name = "Czech" },
			new Language { Id = "dan", Iso639Code = "da", Name = "Danish" },
			new Language { Id = "dut", Iso639Code = "nl", Name = "Dutch" },
			new Language { Id = "eng", Iso639Code = "en", Name = "English" },
			new Language { Id = "epo", Iso639Code = "eo", Name = "Esperanto" },
			new Language { Id = "est", Iso639Code = "et", Name = "Estonian" },
			new Language { Id = "fin", Iso639Code = "fi", Name = "Finnish" },
			new Language { Id = "fre", Iso639Code = "fr", Name = "French" },
			new Language { Id = "glg", Iso639Code = "gl", Name = "Galician" },
			new Language { Id = "geo", Iso639Code = "ka", Name = "Georgian" },
			new Language { Id = "ger", Iso639Code = "de", Name = "German" },
			new Language { Id = "ell", Iso639Code = "el", Name = "Greek" },
			new Language { Id = "heb", Iso639Code = "he", Name = "Hebrew" },
			new Language { Id = "hin", Iso639Code = "hi", Name = "Hindi" },
			new Language { Id = "hun", Iso639Code = "hu", Name = "Hungarian" },
			new Language { Id = "ice", Iso639Code = "is", Name = "Icelandic" },
			new Language { Id = "ind", Iso639Code = "id", Name = "Indonesian" },
			new Language { Id = "ita", Iso639Code = "it", Name = "Italian" },
			new Language { Id = "jpn", Iso639Code = "ja", Name = "Japanese" },
			new Language { Id = "kaz", Iso639Code = "kk", Name = "Kazakh" },
			new Language { Id = "khm", Iso639Code = "km", Name = "Khmer" },
			new Language { Id = "kor", Iso639Code = "ko", Name = "Korean" },
			new Language { Id = "lav", Iso639Code = "lv", Name = "Latvian" },
			new Language { Id = "lit", Iso639Code = "lt", Name = "Lithuanian" },
			new Language { Id = "ltz", Iso639Code = "lb", Name = "Luxembourgish" },
			new Language { Id = "mac", Iso639Code = "mk", Name = "Macedonian" },
			new Language { Id = "may", Iso639Code = "ms", Name = "Malay" },
			new Language { Id = "mal", Iso639Code = "ml", Name = "Malayalam" },
			new Language { Id = "mni", Iso639Code = "ma", Name = "Manipuri" },
			new Language { Id = "mon", Iso639Code = "mn", Name = "Mongolian" },
			new Language { Id = "mne", Iso639Code = "me", Name = "Montenegrin" },
			new Language { Id = "nor", Iso639Code = "no", Name = "Norwegian" },
			new Language { Id = "oci", Iso639Code = "oc", Name = "Occitan" },
			new Language { Id = "per", Iso639Code = "fa", Name = "Persian" },
			new Language { Id = "pol", Iso639Code = "pl", Name = "Polish" },
			new Language { Id = "por", Iso639Code = "pt", Name = "Portuguese" },
			new Language { Id = "pob", Iso639Code = "pb", Name = "Portuguese (BR)" },
			new Language { Id = "rum", Iso639Code = "ro", Name = "Romanian" },
			new Language { Id = "rus", Iso639Code = "ru", Name = "Russian" },
			new Language { Id = "scc", Iso639Code = "sr", Name = "Serbian" },
			new Language { Id = "sin", Iso639Code = "si", Name = "Sinhalese" },
			new Language { Id = "slo", Iso639Code = "sk", Name = "Slovak" },
			new Language { Id = "slv", Iso639Code = "sl", Name = "Slovenian" },
			new Language { Id = "spa", Iso639Code = "es", Name = "Spanish" },
			new Language { Id = "swa", Iso639Code = "sw", Name = "Swahili" },
			new Language { Id = "swe", Iso639Code = "sv", Name = "Swedish" },
			new Language { Id = "syr", Iso639Code = "sy", Name = "Syriac" },
			new Language { Id = "tgl", Iso639Code = "tl", Name = "Tagalog" },
			new Language { Id = "tam", Iso639Code = "ta", Name = "Tamil" },
			new Language { Id = "tel", Iso639Code = "te", Name = "Telugu" },
			new Language { Id = "tha", Iso639Code = "th", Name = "Thai" },
			new Language { Id = "tur", Iso639Code = "tr", Name = "Turkish" },
			new Language { Id = "ukr", Iso639Code = "uk", Name = "Ukrainian" },
			new Language { Id = "urd", Iso639Code = "ur", Name = "Urdu" },
			new Language { Id = "vie", Iso639Code = "vi", Name = "Vietnamese" },
		};
	}
}